dist: precise
language: python
sudo: false
python:
  - 2.7.13

env:
  matrix:
    # This environment tests the newest supported anaconda env
    - DISTRIB="conda" PYTHON_VERSION="2.7"
      NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.16.1"
      SIX_VERSION="1.10.0" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.5"
      NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.16.1"
      SIX_VERSION="1.10.0" COVERAGE="true"
    # This environment tests minimal dependency versions
    - DISTRIB="conda_min" PYTHON_VERSION="2.7"
      SIX_VERSION="1.10.0" NUMPY_VERSION="1.8.2" SCIPY_VERSION="0.14.0" COVERAGE="true"
    - DISTRIB="conda_min" PYTHON_VERSION="3.4"
      SIX_VERSION="1.10.0" NUMPY_VERSION="1.8.2" SCIPY_VERSION="0.14.0" COVERAGE="true"
    # basic Ubuntu build environment
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7"
      NUMPY_VERSION="1.8.2" SCIPY_VERSION="0.14.0" SIX_VERSION="1.10.0"
      COVERAGE="true"

# command to install dependencies
install: source continuous_integration/install.sh
# command to run tests
script: bash continuous_integration/test_script.sh
after_success:
- if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
  