dist: precise
language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - python setup.py test
  